project:
  type: website
  output-dir: docs
  

website:
  title: "Luc Clair"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: {{< fa brands apple >}}
      - href: Research.qmd
        text: Research
      - text: Teaching
        menu:
          - text: Overview
            href: Teaching.qmd 
          - text: Teaching Philosophy
            href: philosophy.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

